version: 0.2

phases:
  install:
    commands:
      # Install the dependencies
      - bash build.sh    
  
  build:
    commands:
      # Create and upload a deployment package
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file template-output.yaml

artifacts:
  files:
    - template-output.yaml
    - config.json    